### ISSUE TITLE
播放个七八分钟之后，就停止播放，不见有继续播放，也不会重新加载

### ISSUE THREAD

**Issue by AAWayne** [Wang454431208/ijkPlayer#1]

**Comment by YueWangChina** [comment]
能否提供下你的视频地址？

**Comment by AAWayne** [comment]
http://live.hkstv.hk.lxdns.com/live/hks/playlist.m3u8

**Comment by AAWayne** [comment]
像m3u8这种片段请求的 ，一旦播放完第一次加载得那一小段，需要自动重新再加载

**Comment by YueWangChina** [comment]
@90candy 我播放没有问题啊,是你网络的问题吧 可以会加载的

**Comment by AAWayne** [comment]
发现模拟器才会存在，真机确实又重新加载了的

**Comment by AAWayne** [comment]
非常棒的播放器，我喜欢这种全屏处理方式
